CREATE TABLE IF NOT EXISTS balances (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    current NUMERIC(18,2) NOT NULL DEFAULT 0,
    withdrawn NUMERIC(18,2) NOT NULL DEFAULT 0
);
